#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : itstool
Version  : 2.0.2
Release  : 8
URL      : http://files.itstool.org/itstool/itstool-2.0.2.tar.bz2
Source0  : http://files.itstool.org/itstool/itstool-2.0.2.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: itstool-bin
Requires: itstool-data
Requires: itstool-doc
Requires: libxml2-python
BuildRequires : libxml2-dev
BuildRequires : libxml2-python

%description


%package bin
Summary: bin components for the itstool package.
Group: Binaries
Requires: itstool-data

%description bin
bin components for the itstool package.


%package data
Summary: data components for the itstool package.
Group: Data

%description data
data components for the itstool package.


%package doc
Summary: doc components for the itstool package.
Group: Documentation

%description doc
doc components for the itstool package.


%prep
%setup -q -n itstool-2.0.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491757981
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1491757981
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/itstool

%files data
%defattr(-,root,root,-)
/usr/share/itstool/its/docbook.its
/usr/share/itstool/its/docbook5.its
/usr/share/itstool/its/its.its
/usr/share/itstool/its/mallard.its
/usr/share/itstool/its/ttml.its
/usr/share/itstool/its/xhtml.its

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
